# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cfn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecfn',
            name='about',
            field=models.TextField(blank=True, max_length=1028, null=True),
        ),
    ]
