# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post')),
            ],
            bases=('posts.post',),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=75),
        ),
    ]
