# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170302_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_a_post',
            field=models.BooleanField(default=False),
        ),
    ]
