# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170215_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_rendered',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Note', 'Note'), ('Project', 'Project'), ('Link', 'Link')], max_length=75),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
