# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_idea_is_a_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='is_a_post',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Note', max_length=75),
        ),
    ]
