# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Note', max_length=75),
        ),
    ]
