# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='test',
            field=models.CharField(default='testField', max_length=10),
        ),
    ]
